import { BusinessPost } from '../../types';

export const mockPosts: BusinessPost[] = [
  {
    id: '1',
    title: '3 BHK Luxury Apartment in Prime Location',
    category: 'property',
    subcategory: 'sale',
    description: 'Spacious 3 BHK apartment with modern amenities, modular kitchen, and parking. Located in the heart of the city with excellent connectivity.',
    price: 8500000,
    images: ['https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg'],
    location: 'Koramangala, Bangalore',
    contact_info: { name: 'Rajesh Kumar', phone: '+91 98765 43210', email: 'rajesh@example.com' },
    user_id: '1',
    status: 'active',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-15T10:30:00Z'
  },
  {
    id: '2',
    title: 'Premium Office Furniture Set - Complete Setup',
    category: 'furniture',
    subcategory: 'sale',
    description: 'Complete office furniture set including executive desk, ergonomic chairs, filing cabinets, and conference table. Excellent condition, barely used.',
    price: 125000,
    images: ['https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg'],
    location: 'Whitefield, Bangalore',
    contact_info: { name: 'Priya Sharma', phone: '+91 98765 43211' },
    user_id: '2',
    status: 'active',
    created_at: '2024-01-14T15:20:00Z',
    updated_at: '2024-01-14T15:20:00Z'
  },
  {
    id: '3',
    title: 'Experienced Real Estate Sales Manager Required',
    category: 'staff',
    subcategory: 'requirement',
    description: 'Looking for an experienced sales manager with 5+ years in real estate. Must have proven track record and excellent communication skills.',
    price: 50000,
    images: [],
    location: 'Mumbai, Maharashtra',
    contact_info: { name: 'Amit Patel', phone: '+91 98765 43212', email: 'amit@realty.com' },
    user_id: '3',
    status: 'active',
    created_at: '2024-01-13T09:45:00Z',
    updated_at: '2024-01-13T09:45:00Z'
  },
  {
    id: '4',
    title: 'Commercial Space for Rent - Prime Business District',
    category: 'property',
    subcategory: 'rent',
    description: '2500 sq ft commercial space ideal for offices or retail. High footfall area with ample parking.',
    price: 85000,
    images: ['https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg'],
    location: 'Connaught Place, Delhi',
    contact_info: { name: 'Sneha Reddy', phone: '+91 98765 43213' },
    user_id: '4',
    status: 'active',
    created_at: '2024-01-12T11:15:00Z',
    updated_at: '2024-01-12T11:15:00Z'
  },
  {
    id: '5',
    title: 'Looking for 2 BHK Apartment in South Delhi',
    category: 'property',
    subcategory: 'requirement',
    description: 'Urgently looking for a well-maintained 2 BHK apartment in South Delhi. Budget up to 25000/month.',
    price: 25000,
    images: [],
    location: 'South Delhi, Delhi',
    contact_info: { name: 'Vikram Singh', phone: '+91 98765 43214' },
    user_id: '5',
    status: 'active',
    created_at: '2024-01-11T16:30:00Z',
    updated_at: '2024-01-11T16:30:00Z'
  },
  {
    id: '6',
    title: 'Modular Kitchen and Home Furniture for Sale',
    category: 'furniture',
    subcategory: 'sale',
    description: 'Complete modular kitchen setup with chimney and hob. Also includes bedroom furniture and dining set.',
    price: 175000,
    images: ['https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg'],
    location: 'Pune, Maharashtra',
    contact_info: { name: 'Anjali Menon', phone: '+91 98765 43215', email: 'anjali@example.com' },
    user_id: '6',
    status: 'active',
    created_at: '2024-01-10T14:00:00Z',
    updated_at: '2024-01-10T14:00:00Z'
  },
  {
    id: '7',
    title: 'Property Documentation Specialist Needed',
    category: 'staff',
    subcategory: 'requirement',
    description: 'Seeking experienced documentation specialist for real estate transactions. Knowledge of legal procedures essential.',
    price: 35000,
    images: [],
    location: 'Chennai, Tamil Nadu',
    contact_info: { name: 'Rahul Verma', phone: '+91 98765 43216' },
    user_id: '7',
    status: 'active',
    created_at: '2024-01-09T10:20:00Z',
    updated_at: '2024-01-09T10:20:00Z'
  },
  {
    id: '8',
    title: 'Luxury Villa with Swimming Pool',
    category: 'property',
    subcategory: 'sale',
    description: 'Beautiful 4 BHK villa with private swimming pool, landscaped garden, and modern amenities. Perfect for families.',
    price: 18500000,
    images: ['https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg'],
    location: 'Hiranandani, Mumbai',
    contact_info: { name: 'Kavita Joshi', phone: '+91 98765 43217', email: 'kavita@homes.com' },
    user_id: '8',
    status: 'active',
    created_at: '2024-01-08T13:45:00Z',
    updated_at: '2024-01-08T13:45:00Z'
  }
];
